image: node:latest

before_script: 
  - apt-get update
  - npm install terser -g

build:
  script:
    - mkdir -p ./Web
    - mkdir -p ./Processor
    - cp -r "./Binaries/Client" "./"
    - cp -r "./Binaries/Server" "./"
    - cp "./Source/Scripts/Configuration/RevCommConfig.php" "./Web/RevCommConfig.php"
    - cp "./Source/Scripts/Communications/RevCommMain.php" "./Web/RevCommMain.php"
    - cp "./Source/Scripts/DataInteract/RevCommData.php" "./Web/RevCommData.php"
    - cp "./Source/Scripts/Processor/RevCommProcessor.rb" "./Processor/RevCommProcessor.rb"
    - cp "./Source/Scripts/Processor/RevCommProxy.php" "./Web/RevCommProxy.php"
    - cp "./Source/Scripts/Processor/RevCommScheduler.php" "./Web/RevCommScheduler.php"
    - terser "./Source/Scripts/Processor/RevCommProcessor.js" --compress --mangle --output "./Processor/RevCommProcessor.min.js"
    - terser "./Source/Scripts/Client/RevCommClient.js" --compress --mangle --output "./Processor/RevCommClient.min.js"
  artifacts: 
    name: "RevCommSuite"
    paths: 
      - Client 
      - Server 
      - Web
      - Processor
      - LICENSE
