name: Main Build
run-name: Main Build
on: [push, workflow_dispatch]
jobs:
  main-build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install terser -g
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: mkdir -p ./Web
      - run: mkdir -p ./Processor
      - run: cp -r "./Application/Binaries/Client" "./"
      - run: cp -r "./Application/Binaries/Server" "./"
      - run: cp "./Application/Scripts/Configuration/RevCommConfig.php" "./Web/RevCommConfig.php"
      - run: cp "./Application/Scripts/Communications/RevCommMain.php" "./Web/RevCommMain.php"
      - run: cp "./Application/Scripts/DataInteract/RevCommData.php" "./Web/RevCommData.php"
      - run: cp "./Application/Scripts/Processor/RevCommProcessor.rb" "./Processor/RevCommProcessor.rb"
      - run: cp "./Application/Scripts/Processor/RevCommProxy.php" "./Web/RevCommProxy.php"
      - run: cp "./Application/Scripts/Processor/RevCommScheduler.php" "./Web/RevCommScheduler.php"
      - run: terser "./Application/Scripts/Processor/RevCommProcessor.js" --compress --mangle --output "./Processor/RevCommProcessor.min.js"
      - run: terser "./Application/Scripts/Client/RevCommClient.js" --compress --mangle --output "./Processor/RevCommClient.min.js"
      - name: Create artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RevCommSuite
          path: |
            Client 
            Server 
            Web
            Processor
            LICENSE
